name: client_app
description: "HR Management System, Client App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  uuid: ^4.5.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.0
flutter:  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
